#!/bin/bash
# CardBrick Sync Daemon Startup Script
# Generated by setup_daemon.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$SCRIPT_DIR/venv-syncd"
DAEMON_DIR="$SCRIPT_DIR/cardbrick-syncd"

# Check if virtual environment exists
if [[ ! -d "$VENV_DIR" ]]; then
    echo "Virtual environment not found! Please run setup_daemon.sh first."
    exit 1
fi

# Set environment variables
export CARDBRICK_DATA_DIR="/var/lib/cardbrick"
export PYTHONPATH="$DAEMON_DIR:$SCRIPT_DIR/cardbrick-cli:$PYTHONPATH"

# Activate virtual environment and run daemon
echo "Starting CardBrick Sync Daemon..."
echo "Data directory: $CARDBRICK_DATA_DIR"
echo "HTTP port: ${CARDBRICK_HTTP_PORT:-6429}"
echo "Press Ctrl+C to stop"
echo

cd "$DAEMON_DIR"
"$VENV_DIR/bin/python" -m main "$@"
